const audioFiles ={
    'Celecoxib - female.wav': require('../assets/audio/Celecoxib - female.wav'),
    'Celecoxib 1 - male.wav': require('../assets/audio/Celecoxib 1 - male.wav'),
    'Chloramphenicol - female.wav': require('../assets/audio/Chloramphenicol - female.wav'),
    'Chloramphenicol 1 - male.wav': require('../assets/audio/Chloramphenicol 1 - male.wav'),
    'Dihydrocodeine - female.wav': require('../assets/audio/Dihydrocodeine - female.wav'),
    //'Dihydrocodeine 1 - male.wav': require('../assets/audio/Dihydrocodeine 1 - male.wav'),
    'Diphenoxylate - female.wav': require('../assets/audio/Diphenoxylate - female.wav'),
    'Diphenoxylate 1 - male.wav': require('../assets/audio/Diphenoxylate 1 - male.wav'),
    'Doxylamine - female.wav': require('../assets/audio/Doxylamine - female.wav'),
   // 'Doxylamine 1 - male.wav': require('../assets/audio/Doxylamine 1 - male.wav'),
    'Famciclovir - female.wav': require('../assets/audio/Famciclovir - female.wav'),
    'Famciclovir 1 - male.wav': require('../assets/audio/Famciclovir 1 - male.wav'),
    'Fluconazole - female.wav': require('../assets/audio/Fluconazole - female.wav'),
    'Fluconazole 1 - male.wav': require('../assets/audio/Fluconazole 1 - male.wav'),
    'Glyceryl trinitrate - female.wav': require('../assets/audio/Glyceryl trinitrate - female.wav'),
    'Glyceryl trinitrate 1 - male.wav': require('../assets/audio/Glyceryl trinitrate 1 - male.wav'),
    'Hydrocortisone - female.wav': require('../assets/audio/Hydrocortisone - female.wav'),
    'Hydrocortisone 1 - male.wav': require('../assets/audio/Hydrocortisone 1 - male.wav'),
    'Ibuprofen - female.wav': require('../assets/audio/Ibuprofen - female.wav'),
    'Ibuprofen 1 - male.wav': require('../assets/audio/Ibuprofen 1 - male.wav'),
    'Levonorgestrel - female.wav': require('../assets/audio/Levonorgestrel - female.wav'),
    'Levonorgestrel 1 - male.wav': require('../assets/audio/Levonorgestrel 1 - male.wav'),
    'Melatonin - female.wav': require('../assets/audio/Melatonin - female.wav'),
    'Melatonin 1 - male.wav': require('../assets/audio/Melatonin 1 - male.wav'),
    'Metoclopramide - female.wav': require('../assets/audio/Metoclopramide - female.wav'),
    //'Metoclopramide 1 - male.wav': require('../assets/audio/Metoclopramide 1 - male.wav'),
    'Naloxone - female.wav': require('../assets/audio/Naloxone - female.wav'),
    'Naloxone 1 - male.wav': require('../assets/audio/Naloxone 1 - male.wav'),
    'Pantoprazole - female.wav': require('../assets/audio/Pantoprazole - female.wav'),
    'Pantoprazole 1 - male.wav': require('../assets/audio/Pantoprazole 1 - male.wav'),
    'Paracetamol - female.wav': require('../assets/audio/Paracetamol - female.wav'),
    'Paracetamol 1 - male.wav': require('../assets/audio/Paracetamol 1 - male.wav'),
    'Prochlorperazine - female.wav': require('../assets/audio/Prochlorperazine - female.wav'),
   // 'Prochlorperazine 1 - male.wav': require('../assets/audio/Prochlorperazine 1 - male.wav'),
    'Promethazine - female.wav': require('../assets/audio/Promethazine - female.wav'),
    'Promethazine 1 - male.wav': require('../assets/audio/Promethazine 1 - male.wav'),
    'Pseudoephedrine - female.wav': require('../assets/audio/Pseudoephedrine - female.wav'),
    'Pseudoephedrine 1 - male.wav': require('../assets/audio/Pseudoephedrine 1 - male.wav'),
    'Salbutamol - female.wav': require('../assets/audio/Salbutamol - female.wav'),
    'Salbutamol 1 - male.wav': require('../assets/audio/Salbutamol 1 - male.wav'),
    'Sumatriptan - female.wav': require('../assets/audio/Sumatriptan - female.wav'),
    'Sumatriptan 1 - male.wav': require('../assets/audio/Sumatriptan 1 - male.wav'),
    'Terbutaline - female.wav': require('../assets/audio/Terbutaline - female.wav'),
    'Terbutaline 1 - male.wav': require('../assets/audio/Terbutaline 1 - male.wav'),
    'Triamcinolone - female.wav': require('../assets/audio/Triamcinolone - female.wav'),
    'Triamcinolone 1 - male.wav': require('../assets/audio/Triamcinolone 1 - male.wav'),
    'Ulipristal - female.wav': require('../assets/audio/Ulipristal - female.wav'),
    'Ulipristal 1 - male.wav': require('../assets/audio/Ulipristal 1 - male.wav'),
};
export default audioFiles;
             